"""Alembic environment.

Migrations connect as ``DATABASE_ADMIN_URL`` -- the owning role. The runtime
role has no DDL rights, so pointing Alembic at ``DATABASE_URL`` would fail with
a permission error rather than silently doing the wrong thing, but being
explicit here means nobody has to discover that.
"""

from __future__ import annotations

import os
from logging.config import fileConfig
from typing import Any

from pgvector.sqlalchemy import VECTOR
from sqlalchemy import engine_from_config, pool

from alembic import context
from app.models import Base  # noqa: F401  (imports every model, populating metadata)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _url() -> str:
    url = os.environ.get("DATABASE_ADMIN_URL") or os.environ.get("DATABASE_URL")
    if not url:
        # Fall back to the .env file so `alembic upgrade head` works the same
        # way the app does, without needing the variable exported by hand.
        from app.core.config import get_settings

        settings = get_settings()
        url = settings.database_admin_url or settings.database_url
    return url


def _render_item(type_: str, obj: Any, autogen_context: Any) -> str | bool:
    """Render pgvector's column type with its own import.

    Alembic renders a type it does not know as ``sa.VECTOR(...)``, which does
    not exist, and the generated revision then fails on import. Naming the real
    module here means an autogenerated revision is correct as written.
    """
    if type_ == "type" and isinstance(obj, VECTOR):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector(dim={obj.dim})"
    return False


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_item=_render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    config.set_main_option("sqlalchemy.url", _url())
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            render_item=_render_item,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
